### ISSUE TITLE
Modal editor appears in bottom corner

### ISSUE THREAD

**Issue by merrill-oakland** [wiris/moodle-atto_wiris#1]
In the current release, when you open the editor in Modal mode, it appears in the bottom right corner of the page, instead of somewhere in the moodle or over the editor.

This is running Moodle 3.2.1+, but on a Clean based theme (not the new Boost themes)

**Comment by manuelwiris** [comment]
@merrill-oakland 

This issue is fixed in our last version (4.2.0). 

Thanks for your feedback.
