### ISSUE TITLE
Cannot be installed on server running PHP 8.1

### ISSUE THREAD

**Issue by phinor** [wiris/moodle-atto_wiris#104]

**Comment by carla-at-wiris** [comment]
Hello @phinor thank you for the feedback,

We are aware that our plugins are not compatible with PHP 8.1 and we are currently working on this. We will provide you more details in the future once the issue gets solved.

**Comment by jguillen-at-wiris** [comment]
Hi @phinor our last releases should have fixed the issue.
Please, feel free to check and update your dependencies if you didn't do it yet.
Thanks!
