### ISSUE TITLE
MathType 8.7.0: error writing to database

### ISSUE THREAD

**Issue by alfredonodo** [wiris/moodle-atto_wiris#116]
Hi,
I have the latest moodle 4.4 on ubuntu 22.04, php 8.1.29 fastCGI mode and mySQL 8.0.36. I have installed MathType by WIRIS 8.7.0.
If I go to Site Administration>Language>Language customisation, I get this error (debugging level>developer):

```
Error writing to database
Debug info: Duplicate entry 'it-238-wirispluginforatto' for key 'mdl_tool_customlang.mdl_toolcust_lancomstr_uix'
INSERT INTO mdl_tool_customlang (lang,componentid,stringid,original,master,timemodified,outdated,local,timecustomized) VALUES(?,?,?,?,?,?,?,?,?)
[array (
0 => 'it',
1 => '238',
2 => 'wirispluginforatto',
3 => 'MathType for Atto',
4 => 'MathType for Atto',
5 => 1717916551,
6 => 0,
7 => NULL,
8 => NULL,
)]
Error code: dmlwriteexception
Stack trace:
line 497 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1482 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 1528 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 208 of /admin/tool/customlang/locallib.php: call to mysqli_native_moodle_database->insert_record()
line 69 of /admin/tool/customlang/index.php: call to tool_customlang_utils::checkout()

Coding error detected, it must be fixed by a programmer: Invalid state passed to moodle_page::set_state. We are in state 3 and state 3 was requested.
Debug info:
Error code: codingerror
Stack trace:
line 1124 of /lib/pagelib.php: coding_exception thrown
line 1541 of /lib/outputrenderers.php: call to moodle_page->set_state()
line 3110 of /lib/outputrenderers.php: call to core_renderer->footer()
line 471 of /lib/setuplib.php: call to core_renderer->fatal_error()
line ? of unknownfile: call to default_exception_handler()
```
Thank you

**Comment by carla-at-wiris** [comment]
Hello @alfredonodo,

Thank you for writing us! We will take a look at this and let you know as soon as we have some information. Any further issues, please feel free to contact with us again.

**Comment by xjiang-at-wiris** [comment]
Hello @alfredonodo,

Sorry to keep you waiting. We set up a similar environment but couldn't reproduce the error.

I found that the official Moodle documentation mentions that if you encounter a `dmlwriteexception` error in MySQL 8, it might be due to the `max_binlog_cache_size` being too small. This can be increased up to a maximum of 4GB on MySQL 8. 

You might want to take a look at this documentation https://docs.moodle.org/404/en/error/moodle/dmlwriteexception

**Comment by alfredonodo** [comment]
Hi,
thank you for your reply. I verified the variabile and [its default value is 4 GB](https://dev.mysql.com/doc/refman/8.4/en/replication-options-binary-log.html#sysvar_max_binlog_cache_size) or 4294967295 (18446744073709547520 on 64 bit system).
Now the problem seems solved with the following configuration: moodle 4.4 on ubuntu 22.04, php 8.1.29 fastCGI mode and mySQL **8.0.39** and MathType by WIRIS 8.7.0. So it could be the mySQL version.
