### ISSUE TITLE
Several JS errors

### ISSUE THREAD

**Issue by nadavkav** [wiris/moodle-atto_wiris#14]
I get the following errors or warnings on the Chrome JS console, though the WIRIS editor seems to work fine. not sure.

editor.html?lang=he&secure=true:55 The key "target-densitydpi" is not supported.
core.js:13 Uncaught TypeError: Cannot read property 'forEach' of undefined
    at core.js:13
(anonymous) @ core.js:13
08550ed…?type=2:69 XHR finished loading: GET "https://petel.weizmann.ac.il/filter/wiris/integration/configurationjs.php".
window.(anonymous function).navigator.(anonymous function).z.(anonymous function).z.(anonymous function).XMLHttpRequest.(anonymous function).(anonymous function) @ 08550ed…?type=2:69
wrs_loadConfiguration @ core.js:2700
(anonymous) @ core.js:2783
editor.html?lang=he&secure=true:1 XMLHttpRequest cannot load https://www.wiris.net/demo/hand/hand.js?httpstatus=true. Request header field X-TS-AJAX-Request is not allowed by Access-Control-Allow-Headers in preflight response.
08550ed…?type=2:69 XHR failed loading: GET "https://www.wiris.net/demo/hand/hand.js?httpstatus=true".
window.(anonymous function).navigator.(anonymous function).z.(anonymous function).z.(anonymous function).XMLHttpRequest.(anonymous function).(anonymous function) @ 08550ed…?type=2:69
com.wiris.system.ServiceProvider.vVl @ editor?lang=he&stats-editor=undefined&stats-mode=safeXml&stats-version=4.7.0.1374:1
com.wiris.system.ServiceProvider.vC3 @ editor?lang=he&stats-editor=undefined&stats-mode=safeXml&stats-version=4.7.0.1374:1
detectHand @ editor?lang=he&stats-editor=undefined&stats-mode=safeXml&stats-version=4.7.0.1374:1
com.wiris.js.JsEditor.vM1.com.wiris.js.JsEditor @ editor?lang=he&stats-editor=undefined&stats-mode=safeXml&stats-version=4.7.0.1374:1
com.wiris.js.JsEditor.newInstance @ editor?lang=he&stats-editor=undefined&stats-mode=safeXml&stats-version=4.7.0.1374:1
wrs_waitForEditor @ editor.js:249
editor.html?lang=he&secure=true:1 XMLHttpRequest cannot load https://www.wiris.net/demo/editor/tick?httpstatus=true. Request header field X-TS-AJAX-Request is not allowed by Access-Control-Allow-Headers in preflight response.
08550ed…?type=2:69 XHR failed loading: GET "https://www.wiris.net/demo/editor/tick?httpstatus=true".
window.(anonymous function).navigator.(anonymous function).z.(anonymous function).z.(anonymous function).XMLHttpRequest.(anonymous function).(anonymous function) @ 08550ed…?type=2:69
com.wiris.system.ServiceProvider.vVl @ editor?lang=he&stats-editor=undefined&stats-mode=safeXml&stats-version=4.7.0.1374:1
com.wiris.system.ServiceProvider.vC3 @ editor?lang=he&stats-editor=undefined&stats-mode=safeXml&stats-version=4.7.0.1374:1
getElement @ editor?lang=he&stats-editor=undefined&stats-mode=safeXml&stats-version=4.7.0.1374:1
wrs_waitForEditor @ editor.js:261
editor.html?lang=he&secure=true:1 XMLHttpRequest cannot load https://www.wiris.net/demo/editor/mathml2internal?httpstatus=true. Request header field X-TS-AJAX-Request is not allowed by Access-Control-Allow-Headers in preflight response.
08550ed…?type=2:69 XHR failed loading: POST "https://www.wiris.net/demo/editor/mathml2internal?httpstatus=true".
window.(anonymous function).navigator.(anonymous function).z.(anonymous function).z.(anonymous function).XMLHttpRequest.(anonymous function).(anonymous function) @ 08550ed…?type=2:69
com.wiris.system.ServiceProvider.vVl @ editor?lang=he&stats-editor=undefined&stats-mode=safeXml&stats-version=4.7.0.1374:1
com.wiris.system.ServiceProvider.vC3 @ editor?lang=he&stats-editor=undefined&stats-mode=safeXml&stats-version=4.7.0.1374:1
setMathML @ editor?lang=he&stats-editor=undefined&stats-mode=safeXml&stats-version=4.7.0.1374:1
setMathML @ editor?lang=he&stats-editor=undefined&stats-mode=safeXml&stats-version=4.7.0.1374:1
wrs_waitForEditor @ editor.js:284

**Comment by nadavkav** [comment]
It seems wiris atto plugin tries to connect wiris.com over http and we are using https, with some restrictions (set by our security team) that might require wiris to communicate to an https service on your end. is this possible?

**Comment by nadavkav** [comment]
Purging the Chrome browser several times, seems to resolve those issues. weird.
I am only left with:

Uncaught TypeError: Cannot read property 'forEach' of undefined
    at core.js:13
(anonymous) @ core.js:13
core.js:2700 XHR finished loading: GET "https://petel.weizmann.ac.il/filter/wiris/integration/configurationjs.php".
wrs_loadConfiguration @ core.js:2700
(anonymous) @ core.js:2783

**Comment by manuelwiris** [comment]
@nadavkav 

WIRIS PLUGIN should be able to detect if you are using in http or https and connect to our services choosing the correct protocol. We will further investigate this issue. 

Thanks for your feedback.

**Comment by nadavkav** [comment]
Looking deeper in the communication, I can see it detects it correctly now. not sure why I got those first errors in the first place.

@manuelwiris thank you for your quick reply!

**Comment by manuelwiris** [comment]
@nadavkav  thanks for your feedback.

This issue is still open until we check that we are choosing the correct protocol calling WIRIS services.

**Comment by dcanetma** [comment]
This issue should be fixed by now.
Let us know if it's still happening.
