### ISSUE TITLE
Inserting HTML into textarea causing quiz not saving

### ISSUE THREAD

**Issue by pingtaoye** [wiris/moodle-atto_wiris#17]
Installed the latest Wiris Atto editor plugin, when you created a new quiz, you have to hit backspace once in the text area in the feedback section. Otherwise, there is "You must fill in the feedback boxes without leaving any gaps." error. Everything works fine if I removed this plugin.
To replicate this issue:
With this WIRIS Atto plugin installed, go to create a quiz, give a name then hit save directly. The error message pops up. 
![editing quiz 1](https://user-images.githubusercontent.com/17863517/32071978-eeed16b0-ba45-11e7-98c3-bbd59548795d.jpg)

**Comment by manuelwiris** [comment]
Hi @pingtaoye 

Thanks for your feedback, 

This issue is solved in our latest version #16 

Thanks for your feedback,
