### ISSUE TITLE
undefined strings

### ISSUE THREAD

**Issue by Syxton** [wiris/moodle-atto_wiris#31]
Latest version, I'm seeing undefined window modal title and button text.
![capture](https://user-images.githubusercontent.com/989354/40937708-85222420-680d-11e8-92ac-c9d13f8449ed.PNG)

**Comment by manuelwiris** [comment]
Hi, @Syxton,

Have you tried to delete de JavaScript cache?  #30 changes the JavaScript API related to strings and translations.

Please let us know if the issue can be reproduced with the cache deleted. 

Best,

**Comment by Syxton** [comment]
@manuelwiris I purged Moodle cache multiple times yesterday, but this morning after clearing cache again it seems to be pulling the strings now.  Thanks!
