### ISSUE TITLE
Multiple editors on screen issue (MAJOR)

### ISSUE THREAD

**Issue by Syxton** [wiris/moodle-atto_wiris#39]
If multiple editors are on screen at the same time (quiz for instance), the MathType editor opens but it will only inject it's code into the final editor on the screen.

This only occurs with the ATTO editor plugin.

**Comment by manuelwiris** [comment]
Hy  @Syxtonm and thanks for your feedback.

We can't reproduce your issue in our end. We try editing a quiz (using description and feedback editors) and a question type. Which version of the plugin and Moodle are you using?

Thanks in advance,

**Comment by Syxton** [comment]
@manuelwiris 
We are using Moodle 3.5.1+, latest version of WIRIS 7.6.1.  I create a quiz with 2 essay questions on the same page.  Try to enter data using WIRIS editor in question 1, data gets entered in question 2.

**Comment by Syxton** [comment]
[https://rose-hulman.hosted.panopto.com/Panopto/Pages/Viewer.aspx?id=7be25d9a-18c8-450b-91d9-a96d012bd100](url)

**Comment by manuelwiris** [comment]
@Syxton Finally we can reproduce the issue in our end. We are listening 'onChange' event to know the active editor, but the only 'onChange' event triggered is the event of the last editor. 

The workaround will be available in our next release, we want to have it ready at the end of this week.

Thanks for your feedback.

**Comment by Syxton** [comment]
Seems to be fixed in the latest release.  Thanks!
