### ISSUE TITLE
core.js in .gitignore

### ISSUE THREAD

**Issue by birdy4012** [wiris/moodle-atto_wiris#51]
hi,
is it normal that core.js is in .gitignore ?

**Comment by manuelwiris** [comment]
Hi @birdy4012 

Yes. core.js is our JavaScript library, which we are using among different integrations.  The JavaScript library code is here: http://github.com/wiris/mathtype-integration-js-dev

It would a good idea, to avoid misunderstandings, update the third party lib file to add the core file. We will include the update in our next release. 

Thanks for your feedback.

**Comment by birdy4012** [comment]
ok thanks.
it's just surprising because when we deploy our Moodle update via Git, we lose the main file of your plugin.
But it's ok, we had to manually add this file for the plugin works.

PS: we don't see thirdpartylibs.php. Only thirdpartylibs**.xml**. It's correct ?

**Comment by manuelwiris** [comment]
Yes, you are right is thirdpartylibs.xml file, which serves to inlcude third party libraries in a [Plugin](https://docs.moodle.org/dev/Third_Party_Libraries)

I was thinking about your issue and I have come to the conclusion that is better to remove core.js from .gitignore. When we add it to .gitignore we don't think about the installations using GIT. 

I'll reopen the issue.

**Comment by dcanetma** [comment]
I'm closing the issue since it does not apply anymore.
