### ISSUE TITLE
Update Wiris to use AMD modules + jQuery instead of YUI

### ISSUE THREAD

**Issue by danowar2k** [wiris/moodle-atto_wiris#57]
Please update your javascript sources to use the (as of Moodle 3.2 at least) standard of AMD modules + jQuery instead of YUI. Moodle has deprecated usage of YUI and is internally migrating to AMD modules.

I don't know how much work this entails, though. I've migrated one Moodle plugin to require.js and that went relatively fast. Your miles may vary.

**Comment by manuelwiris** [comment]
HI @danowar2k 

Despite Moodle recommends the use of the AMD + jQuery, is not possible to do it with Atto plugins because the Atto API is still using YUI. 

I'll close this issue.

Thanks for your feedback.
