### ISSUE TITLE
I am getting a lot of security warnings about package.json

### ISSUE THREAD

**Issue by nadavkav** [wiris/moodle-atto_wiris#68]
Running SNYK (https://snyk.io/) security scanning tool, I am getting a lot of severe warning issues about the packages used in WIRIS.
Attaching the report
[screencapture-app-snyk-io-org-nadavkav-project-90c0e848-0144-42c0-9919-c9d42dda3ab7-2020-09-09-13_57_43.pdf](https://github.com/wiris/moodle-atto_wiris/files/5194640/screencapture-app-snyk-io-org-nadavkav-project-90c0e848-0144-42c0-9919-c9d42dda3ab7-2020-09-09-13_57_43.pdf)
Please advise

**Comment by dcanetma** [comment]
You're right.

The reference to the MathType Web Integration JavaScript SDK is outdated, and needs to be updated.

We'll work on it. 

Many thanks for reporting the issue.

**Comment by nadavkav** [comment]
Thank you @dcanetma :smile:

**Comment by dcanetma** [comment]
Node.js third-party vulnerabilites have been fixed on the lastest version of this plugin.
```

$ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 45 scanned packages
```
