### ISSUE TITLE
Equations are not saved, when giving feedback

### ISSUE THREAD

**Issue by superfoght** [wiris/moodle-atto_wiris#69]
I have an issue on assignments, when giving feedback. The format of the equations are not saved. It's reverted back to plaintext when I save the feedback. 

See an example in this video: https://www.loom.com/share/bfe44c06674741fa935bace1ee84ca12

**Comment by dcanetma** [comment]
Thanks for reporting the issue!
The video is very helpful.

Could you tell what version of Moodle are you using and if which versions of the 'moodle-atto_wiris' and 'moodle-filter_wiris' are you using?

**Comment by superfoght** [comment]
Yes of course. 

Moodle version is 3.8.4
moodle-atto_wiris: 7.24.0 (2020090300)
moodle-filter_wiris: 7.24.0 (2020090300)

**Comment by dcanetma** [comment]
Thanks!

**Comment by dcanet-at-wiris** [comment]
The last release should solve the issue.

We've included a behat test to validate it.

Here's a video showing the fix.


https://user-images.githubusercontent.com/85346791/122558562-843be680-d03e-11eb-940d-63231e651fe3.mp4
