### ISSUE TITLE
en_us lang pack does not exist

### ISSUE THREAD

**Issue by Syxton** [wiris/moodle-atto_wiris#7]
We run the en_us lang pack.  The wiris plugin doesn't have a wiris/lang/en_us folder.  I copied the en lang folder and made a en_us folder and it worked.

**Comment by Syxton** [comment]
Fix would be to add the following in the wrs_loadLangFile() of core.js

    var http = new XMLHttpRequest();
    http.open('HEAD', wrs_getCorePath() + "/lang/" + _wrs_int_langCode + "/strings.js", false);
    http.send();
    if (http.status == 404) {
         _wrs_int_langCode = 'en';    
    }

**Comment by manuelwiris** [comment]
Hi @Syxton , 

Thanks for your feedback and your contribution. We will incorporate your changes in our next release.

Best regards,

**Comment by birdy4012** [comment]
This issue is for any "sublanguage" (for us: fr_CA). __wrs_int_langCode_ is too in editor.js, function wrs_waitForCore()

**Comment by manuelwiris** [comment]
Hi this issue with "sublanguages" is solved in our last version; #12
