### ISSUE TITLE
CSS syntax error

### ISSUE THREAD

**Issue by birdy4012** [wiris/moodle-atto_wiris#9]
Hi, I think we have some syntax error in CSS files :
In modal.css :
.wrs_modal_dialogContainer.wrs_drag. {  => last "."
In editor.js :
..wrs_buttonContainer.wrs_modalDesktop { => ".." in start of line

**Comment by manuelwiris** [comment]
Hi @birdy4012 and thanks for your feedback

This issue has been fixed in our last version: #12 

Best,
