### ISSUE TITLE
Wrongly named file: tests/behat/atto_pluginCompatibility_multilang2.featur_

### ISSUE THREAD

**Issue by Julian-Tovar** [wiris/moodle-atto_wiris#93]
Good day team. The Behat test file 'atto_pluginCompatibility_multilang2.featur_' has a bad extension name. It ends in '.featur_', but it should end in '.feature'.

You can see this by going to https://github.com/wiris/moodle-atto_wiris/tree/stable/tests/behat

I created a Behat test site using Moodle with version 4.0. Then renamed the file to have the '.feature' extension, and the test fails:

<img width="1353" alt="Screen Shot 2022-05-24 at 9 39 24 AM" src="https://user-images.githubusercontent.com/89230550/170062711-1b6223b6-27dd-4399-8bc3-c1f1e64a6d71.png">

My guess is that whichever testing tool you use to run Behat tests, did not detect this file as a Behat test file, and so it was ignored. I say this because this is the only test that fails on Moodle 4.0.

Thank you.

**Comment by carla-at-wiris** [comment]
Hi @Julian-Tovar!

Thank you for writing us. We have changes all of our test suites lately, so we will be closing this issue.

If you need further assistance here, feel free to reopen this issue or contact us at [support@wiris.com](mailto:support@wiris.com).
