### ISSUE TITLE
Four Behat tests failing in Moodle 3.11

### ISSUE THREAD

**Issue by Julian-Tovar** [wiris/moodle-atto_wiris#94]
Good day, there are 4 atto_wiris Behat tests failing on Moodle 3.11.

These 4 tests pass on Moodle 4.0, which leads me to believe that maybe these tests make use of new Moodle 4.0 features. But I'm opening this ticket because the atto_wiris plugin is advertised as compatible with Moodle 3.11 (which can be seen here: https://moodle.org/plugins/atto_wiris/versions).

The failing tests are the following:

1. lib/editor/atto/plugins/wiris/tests/behat/atto_filterActivityDisabled.feature:23

Feature: Check MathType disabled if filter disabled at activity forum level
Scenario: Disable MathType at activity level

Screenshot of failure:
<img width="1214" alt="Screen Shot 2022-05-24 at 11 59 46 AM" src="https://user-images.githubusercontent.com/89230550/170094877-99a07e0d-4aee-4b23-adc4-4a0b4e21d6f7.png">

2. lib/editor/atto/plugins/wiris/tests/behat/atto_emptyLatex.feature:20

Feature: Check empty LaTeX edition
Scenario: Insert MathType formula to an empty LaTeX

Screenshot of failure:
<img width="1300" alt="Screen Shot 2022-05-24 at 12 06 10 PM" src="https://user-images.githubusercontent.com/89230550/170101466-ddff6c66-7429-4f82-acdc-9ea990cb314c.png">

3. lib/editor/atto/plugins/wiris/tests/behat/atto_multipleEditorsTextAarea.feature:20

Feature: Checks formula creation in forms with multiple editors
Scenario: Create and answer a Quiz using formulas

Screenshot of failure:
<img width="1302" alt="Screen Shot 2022-05-24 at 12 09 31 PM" src="https://user-images.githubusercontent.com/89230550/170101788-0528b441-3bc4-471f-8bc9-406f03c1ea9e.png">

4. lib/editor/atto/plugins/wiris/tests/behat/atto_assignmentsGiveFeedback.feature:27

Feature: Formulas are rendered on an Assignment feedback
Scenario: Grade an assignment with a Formula and ensure it display correctly in the gradebook

Screenshot of failure:
<img width="1300" alt="Screen Shot 2022-05-24 at 12 11 07 PM" src="https://user-images.githubusercontent.com/89230550/170102024-9fa071e4-8ae8-4a6e-bc76-85597b806759.png">

These 4 failures cause a Behat build to fail, when executing such a build on a Moodle 3.11 system.

Thank you so much for your attention to this issue.

**Comment by carla-at-wiris** [comment]
Hi @Julian-Tovar!

Thank you for writing us. We have changed all of our test suites lately, so we will be closing this issue.

If you need further assistance here, feel free to reopen this issue or contact us at [support@wiris.com](mailto:support@wiris.com).
